#!/bin/bash
INPUT_DIR=$1
OUTPUT_DIR=$2
#DURATION=$3
#mkdir $OUTPUT_DIR


for filePath in $1/perf.data.*; do
	fileName=$(basename -- "$filePath")
	outputFile=$filePath.txt

    perf report --stdio --sort dso -g folded -i $filePath | grep "^[  ]" | awk '{print $3 "\t" $2}' | grep -v "0.00" | grep -v "0.01" | grep -v "0.02" | grep -v "0.03" | grep -v "0.04" > $outputFile 
    cat $outputFile >> $OUTPUT_DIR
done

#sudo chown $USER $2/*

